// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "./include/image_picker_ios/messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation FLTSourceCamera_V2Box
- (instancetype)initWithValue:(FLTSourceCamera_V2)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation FLTSourceType_V2Box
- (instancetype)initWithValue:(FLTSourceType_V2)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface FLTMaxSize_V2 ()
+ (FLTMaxSize_V2 *)fromList:(NSArray<id> *)list;
+ (nullable FLTMaxSize_V2 *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTMediaSelectionOptions_V2 ()
+ (FLTMediaSelectionOptions_V2 *)fromList:(NSArray<id> *)list;
+ (nullable FLTMediaSelectionOptions_V2 *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface FLTSourceSpecification_V2 ()
+ (FLTSourceSpecification_V2 *)fromList:(NSArray<id> *)list;
+ (nullable FLTSourceSpecification_V2 *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation FLTMaxSize_V2
+ (instancetype)makeWithWidth:(nullable NSNumber *)width
    height:(nullable NSNumber *)height {
  FLTMaxSize_V2* pigeonResult = [[FLTMaxSize_V2 alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (FLTMaxSize_V2 *)fromList:(NSArray<id> *)list {
  FLTMaxSize_V2 *pigeonResult = [[FLTMaxSize_V2 alloc] init];
  pigeonResult.width = GetNullableObjectAtIndex(list, 0);
  pigeonResult.height = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable FLTMaxSize_V2 *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTMaxSize_V2 fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.width ?: [NSNull null],
    self.height ?: [NSNull null],
  ];
}
@end

@implementation FLTMediaSelectionOptions_V2
+ (instancetype)makeWithMaxSize:(FLTMaxSize_V2 *)maxSize
    imageQuality:(nullable NSNumber *)imageQuality
    requestFullMetadata:(BOOL )requestFullMetadata
    allowMultiple:(BOOL )allowMultiple
    limit:(nullable NSNumber *)limit {
  FLTMediaSelectionOptions_V2* pigeonResult = [[FLTMediaSelectionOptions_V2 alloc] init];
  pigeonResult.maxSize = maxSize;
  pigeonResult.imageQuality = imageQuality;
  pigeonResult.requestFullMetadata = requestFullMetadata;
  pigeonResult.allowMultiple = allowMultiple;
  pigeonResult.limit = limit;
  return pigeonResult;
}
+ (FLTMediaSelectionOptions_V2 *)fromList:(NSArray<id> *)list {
  FLTMediaSelectionOptions_V2 *pigeonResult = [[FLTMediaSelectionOptions_V2 alloc] init];
  pigeonResult.maxSize = GetNullableObjectAtIndex(list, 0);
  pigeonResult.imageQuality = GetNullableObjectAtIndex(list, 1);
  pigeonResult.requestFullMetadata = [GetNullableObjectAtIndex(list, 2) boolValue];
  pigeonResult.allowMultiple = [GetNullableObjectAtIndex(list, 3) boolValue];
  pigeonResult.limit = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable FLTMediaSelectionOptions_V2 *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTMediaSelectionOptions_V2 fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.maxSize ?: [NSNull null],
    self.imageQuality ?: [NSNull null],
    @(self.requestFullMetadata),
    @(self.allowMultiple),
    self.limit ?: [NSNull null],
  ];
}
@end

@implementation FLTSourceSpecification_V2
+ (instancetype)makeWithType:(FLTSourceType_V2)type
    camera:(FLTSourceCamera_V2)camera {
  FLTSourceSpecification_V2* pigeonResult = [[FLTSourceSpecification_V2 alloc] init];
  pigeonResult.type = type;
  pigeonResult.camera = camera;
  return pigeonResult;
}
+ (FLTSourceSpecification_V2 *)fromList:(NSArray<id> *)list {
  FLTSourceSpecification_V2 *pigeonResult = [[FLTSourceSpecification_V2 alloc] init];
  FLTSourceType_V2Box *boxedFLTSourceType_V2 = GetNullableObjectAtIndex(list, 0);
  pigeonResult.type = boxedFLTSourceType_V2.value;
  FLTSourceCamera_V2Box *boxedFLTSourceCamera_V2 = GetNullableObjectAtIndex(list, 1);
  pigeonResult.camera = boxedFLTSourceCamera_V2.value;
  return pigeonResult;
}
+ (nullable FLTSourceSpecification_V2 *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [FLTSourceSpecification_V2 fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[FLTSourceType_V2Box alloc] initWithValue:self.type],
    [[FLTSourceCamera_V2Box alloc] initWithValue:self.camera],
  ];
}
@end

@interface FLTMessagesPigeonCodecReader_V2 : FlutterStandardReader
@end
@implementation FLTMessagesPigeonCodecReader_V2
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[FLTSourceCamera_V2Box alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[FLTSourceType_V2Box alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: 
      return [FLTMaxSize_V2 fromList:[self readValue]];
    case 132: 
      return [FLTMediaSelectionOptions_V2 fromList:[self readValue]];
    case 133: 
      return [FLTSourceSpecification_V2 fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTMessagesPigeonCodecWriter_V2 : FlutterStandardWriter
@end
@implementation FLTMessagesPigeonCodecWriter_V2
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTSourceCamera_V2Box class]]) {
    FLTSourceCamera_V2Box *box = (FLTSourceCamera_V2Box *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[FLTSourceType_V2Box class]]) {
    FLTSourceType_V2Box *box = (FLTSourceType_V2Box *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[FLTMaxSize_V2 class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTMediaSelectionOptions_V2 class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTSourceSpecification_V2 class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTMessagesPigeonCodecReader_V2Writer : FlutterStandardReaderWriter
@end
@implementation FLTMessagesPigeonCodecReader_V2Writer
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTMessagesPigeonCodecWriter_V2 alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTMessagesPigeonCodecReader_V2 alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTGetMessagesCodec_V2(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTMessagesPigeonCodecReader_V2Writer *readerWriter = [[FLTMessagesPigeonCodecReader_V2Writer alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpFLTImagePickerApi_V2(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTImagePickerApi_V2> *api) {
  SetUpFLTImagePickerApi_V2WithSuffix(binaryMessenger, api, @"");
}

void SetUpFLTImagePickerApi_V2WithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTImagePickerApi_V2> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.image_picker_ios_chat_v2.ImagePickerApi_V2.pickImage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec_V2()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pickImageWithSource:maxSize:quality:fullMetadata:completion:)], @"FLTImagePickerApi_V2 api (%@) doesn't respond to @selector(pickImageWithSource:maxSize:quality:fullMetadata:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTSourceSpecification_V2 *arg_source = GetNullableObjectAtIndex(args, 0);
        FLTMaxSize_V2 *arg_maxSize = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_imageQuality = GetNullableObjectAtIndex(args, 2);
        BOOL arg_requestFullMetadata = [GetNullableObjectAtIndex(args, 3) boolValue];
        [api pickImageWithSource:arg_source maxSize:arg_maxSize quality:arg_imageQuality fullMetadata:arg_requestFullMetadata completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.image_picker_ios_chat_v2.ImagePickerApi_V2.pickMultiImage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec_V2()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pickMultiImageWithMaxSize:quality:fullMetadata:limit:completion:)], @"FLTImagePickerApi_V2 api (%@) doesn't respond to @selector(pickMultiImageWithMaxSize:quality:fullMetadata:limit:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTMaxSize_V2 *arg_maxSize = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_imageQuality = GetNullableObjectAtIndex(args, 1);
        BOOL arg_requestFullMetadata = [GetNullableObjectAtIndex(args, 2) boolValue];
        NSNumber *arg_limit = GetNullableObjectAtIndex(args, 3);
        [api pickMultiImageWithMaxSize:arg_maxSize quality:arg_imageQuality fullMetadata:arg_requestFullMetadata limit:arg_limit completion:^(NSArray<NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.image_picker_ios_chat_v2.ImagePickerApi_V2.pickVideo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec_V2()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pickVideoWithSource:maxDuration:completion:)], @"FLTImagePickerApi_V2 api (%@) doesn't respond to @selector(pickVideoWithSource:maxDuration:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTSourceSpecification_V2 *arg_source = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_maxDurationSeconds = GetNullableObjectAtIndex(args, 1);
        [api pickVideoWithSource:arg_source maxDuration:arg_maxDurationSeconds completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.image_picker_ios_chat_v2.ImagePickerApi_V2.pickMultiVideo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec_V2()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pickMultiVideoWithMaxDuration:limit:completion:)], @"FLTImagePickerApi_V2 api (%@) doesn't respond to @selector(pickMultiVideoWithMaxDuration:limit:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSNumber *arg_maxDurationSeconds = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_limit = GetNullableObjectAtIndex(args, 1);
        [api pickMultiVideoWithMaxDuration:arg_maxDurationSeconds limit:arg_limit completion:^(NSArray<NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Selects images and videos and returns their paths.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.image_picker_ios_chat_v2.ImagePickerApi_V2.pickMedia", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:FLTGetMessagesCodec_V2()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pickMediaWithMediaSelectionOptions:completion:)], @"FLTImagePickerApi_V2 api (%@) doesn't respond to @selector(pickMediaWithMediaSelectionOptions:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FLTMediaSelectionOptions_V2 *arg_mediaSelectionOptions = GetNullableObjectAtIndex(args, 0);
        [api pickMediaWithMediaSelectionOptions:arg_mediaSelectionOptions completion:^(NSArray<NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
